[package]
name = "zfs_recovery_rs"
version = "0.1.0"
edition = "2021"

[dependencies]
serde_json = "1.0.138"
winapi = { version = "0.3", features = ["fileapi", "ioapiset", "handleapi", "winbase", "errhandlingapi"] }
